### ISSUE TITLE
How can i get the selected menu item index or position?

### ISSUE THREAD

**Issue by hassan31** [Commit451/ModalBottomSheetDialogFragment#6]
Hi, I want the selected index or position in Option Object. How can I get this?

Kind Regards,
Hassan

**Comment by Jawnnypoo** [comment]
Hey, you can just use the `id` for this, setting each ID to the position or index.

**Comment by ola0x** [comment]
Yeah that's true 
I created a GitHub gist to show the implementation, find it here
https://gist.github.com/OlaOlaoni/cadf63a95ad9a6b88cdc70631da6f5b8
